apiVersion: v1
kind: Service
metadata:
  name: cloudshirt-service
  labels:
    app: cloudshirt
spec:
  selector:
    app: cloudshirt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5200
    - protocol: TCP
      port: 80
      targetPort: 5106
  type: LoadBalancer
