apiVersion: v1
kind: Service
metadata:
  name: cloudshirt-service
  labels:
    app: cloudshirt
spec:
  selector:
    app: cloudshirt
  ports:
    - name: port1
      protocol: TCP
      port: 80
      targetPort: 5200
    - name: port2
      protocol: TCP
      port: 81
      targetPort: 5106
  type: LoadBalancer
