apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudshirt-deployment
  labels:
    app: cloudshirt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudshirt
  template:
    metadata:
      labels:
        app: cloudshirt
    spec:
      containers:
      - name: cloudshirt
        image: franko2147/cloudautomation:publicapi
        ports: 5200
      - name: webmvc
        image: franko2147/cloudautomation:webmvc
        ports: 5106
